service: ${self:custom.name}
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
plugins:
  - serverless-nextjs-plugin
custom:
  name: webapp
  serverless-nextjs:
    assetsBucketName: 'webapp-assets-${self:provider.stage}'
package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**